apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-puzzle-solver-frontend
spec:
  replicas: 1
  template:
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
